require('plugins')
require('treesitter-config')
require('dashboard-config')
require('tokyonight-config')
require('floaterm')
require('babar')
require('telescope-config')
-- require('dap')
require('autosave')
require('icons')
require('nvim-tree-config')
-- require('providers')
require('gitsigns-config')
require('utils')
require('settings')
require('mappings')
require('gui')
-- require('hgalaxyline')
-- require('compe-config')
require('autopairs-config')
-- require('lspkind-config')
require('lsp')
require('colorizer-config')
require('indentline')
require('config-notify')
require('lualine-config')
-- require('wildermenu-config')
-- require('alpha-nvim-config')
-- require('cmdline')
require('config-noice')
require('devscript')
require('latextoillustrator')
require('transparent-config')
-- require('alpha-nvim-config')


